resource_registry:
#  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/rhosp15/my-overcloud/network/config/single-nic-vlans/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/rhosp15/my-overcloud/network/config/single-nic-vlans/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/rhosp15/my-overcloud/network/config/single-nic-vlans/controller.yaml
#  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/rhosp15/my-overcloud/network/config/single-nic-vlans/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/rhosp15/my-overcloud/network/config/single-nic-vlans/ceph-storage.yaml
  OS::TripleO::NodeUserData: /home/stack/rhosp15/my-overcloud/swap.yaml
  OS::TripleO::Services::Fluentd: /home/stack/rhosp15/my-overcloud/deployment/deprecated/logging/fluentd-container-puppet.yaml
  OS::TripleO::Services::SensuClient: /home/stack/rhosp15/my-overcloud/deployment/deprecated/monitoring/sensu-client-container-puppet.yaml
  OS::TripleO::Services::Collectd: /home/stack/rhosp15/my-overcloud/deployment/metrics/collectd-container-puppet.yaml
parameter_defaults:
  # Customize all these values to match the local environment
  InternalApiNetCidr: 172.17.0.0/24
  StorageNetCidr: 172.18.0.0/24
  StorageMgmtNetCidr: 172.19.0.0/24
  TenantNetCidr: 172.16.0.0/24
  ExternalNetCidr: 192.168.122.0/24
  InternalApiAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  TenantAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  # Use an External allocation pool which will leave room for floating IPs
  ExternalAllocationPools: [{'start': '192.168.122.130', 'end': '192.168.122.150'}]
  InternalApiNetworkVlanID: 201
  StorageNetworkVlanID: 202
  StorageMgmtNetworkVlanID: 203
  TenantNetworkVlanID: 204
  ExternalNetworkVlanID: 100
  DnsServers: ["8.8.8.8","8.8.4.4"]
  EC2MetadataIp: 192.0.2.1
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 192.168.122.1
  ControlPlaneDefaultRoute: 192.0.2.1
  # Customize bonding options if required (will be ignored if bonds are not used)
  BondInterfaceOvsOptions:
      "bond_mode=balance-tcp lacp=active other-config:lacp-fallback-ab=true"
  NovaComputeExtraConfig:
    nova::compute::reserved_host_memory: 512
  DockerInsecureRegistryAddress:
    - brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888
    - 192.0.2.1:8787
  SELinuxMode: permissive
  PythonInterpreter: /usr/bin/python3
  NovaComputeLibvirtType: qemu
  LoggingServers:
    - host: log0.example.com
      port: 24224
    - host: log1.example.com
      port: 24224
  MonitoringRabbitHost: 10.10.10.10
  MonitoringRabbitPort: 5672
  MonitoringRabbitUserName: sensu
  MonitoringRabbitPassword: sensu
  MonitoringRabbitUseSSL: true
  MonitoringRabbitVhost: "/sensu"
  SensuClientCustomConfig:
    api:
      warning: 10
      critical: 20
  CollectdDefaultPlugins:
    - disk
    - interface
    - load
    - memory
    - processes
    - tcpconns
  CollectdExtraPlugins:
    - disk
    - df
  CollectdServer: collectd0.example.com
  CollectdServerPort: 25826
  CollectdSecurityLevel: None
